on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Test
      run: go test -race ./...
      